// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="mux,hls_ip_2019_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7vx485t-ffg1157-1,HLS_INPUT_CLOCK=100.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=0.475000,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=0,HLS_SYN_LUT=16,HLS_VERSION=2019_2}" *)

module mux (
        selrc,
        adb_V,
        ada_V,
        ad_V
);


input   selrc;
input  [7:0] adb_V;
input  [7:0] ada_V;
output  [15:0] ad_V;

wire   [0:0] v2_V_fu_57_p0;
wire   [0:0] v1_V_fu_65_p0;
wire   [7:0] v1_V_fu_65_p3;
wire   [7:0] v2_V_fu_57_p3;

assign ad_V = {{v1_V_fu_65_p3}, {v2_V_fu_57_p3}};

assign v1_V_fu_65_p0 = selrc;

assign v1_V_fu_65_p3 = ((v1_V_fu_65_p0[0:0] === 1'b1) ? ada_V : adb_V);

assign v2_V_fu_57_p0 = selrc;

assign v2_V_fu_57_p3 = ((v2_V_fu_57_p0[0:0] === 1'b1) ? adb_V : ada_V);

endmodule //mux
